version: '3.8'

services:
  vectorization_server:
    container_name: vectorization-server-${PROJECT_NAME}
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    restart: always
    volumes:
      - ./backend:/code
    expose:
      - 8000
    ports:
      - 8001:8000
    env_file: .env
